#!/bin/sh

# Disable core dump
# shellcheck disable=SC3045
ulimit -Sc 0

# X
xset dpms
xset b off
xset r rate 210 40
xset s off

# Enable scrolling for ThinkPad by dragging trackpoint with the middle button
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5

# Set keyboard layouts and caps as ctrl
setxkbmap \
	-layout "us,ru" \
	-option "grp:alt_shift_toggle" \
	-option "ctrl:nocaps"

# Load resources
xrdb -merge "$HOME/.config/x11/xresources"

. "$HOME/.config/x11/xprofile"
ssh-agent dwm
